### ISSUE TITLE
 The environment variable SECRET_KEY does not contain a valid JSON string.

### ISSUE THREAD

**Issue by naimulemon** [phryneas/ssr-only-secrets#3]
```
  const sessionId = await readSSROnlySecret(
      // @ts-ignore
      await cloakedSessionId,
      "SECRET_KEY"
    );
```
`SECRET_KEY="secret"
`

` ⨯ Error: The environment variable SECRET_KEY does not contain a valid JSON string.`

**Comment by phryneas** [comment]
Yes, as per the [README](https://github.com/phryneas/ssr-only-secrets?tab=readme-ov-file#usage) you need a jwk-formatted AES-CBC key.
